application: bananasbrownies
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /stylesheet
  static_dir: stylesheet

- url: /images
  static_dir: images
  
- url: /javascript
  static_dir: javascript
  
- url: /rpc
  script: RPCHandler.py
  
- url: /.*
  script: default.py